-- Creates the clean historical GL coding table used for retrieval and training context.
-- Replace placeholders before execution:
--   {{PROJECT_ID}}, {{DATASET_ID}}, {{RAW_GL_TABLE}}

CREATE OR REPLACE TABLE `{{PROJECT_ID}}.{{DATASET_ID}}.gl_coding_history` AS
WITH source_gl AS (
  SELECT
    *,
    CAST(ACCOUNT AS STRING) AS account_text,
    CAST(DEPARTMENT AS STRING) AS department_text,
    CONCAT(
      COALESCE(CAST(SUPPLIER_CUSTMER_NAME AS STRING), ''),
      ' | ',
      COALESCE(CAST(GL_LINE_DESCRIPTION AS STRING), ''),
      ' | ',
      COALESCE(CAST(HFM_DSCRIPTIONS AS STRING), '')
    ) AS embedding_text
  FROM `{{PROJECT_ID}}.{{DATASET_ID}}.{{RAW_GL_TABLE}}`
),
clean_gl AS (
  SELECT
    TO_HEX(SHA256(TO_JSON_STRING(STRUCT(
      ENTITY,
      GL_SOURCE_NAME,
      GL_CATEGORY,
      JOURNAL_NUMBER,
      BOOKING_DATE,
      PERIOD,
      ACCOUNT,
      HFM_ACCOUNT,
      DEPARTMENT,
      PRODUCT,
      IC,
      PROJECT,
      SYSTEM,
      RESERVE,
      INVOICE_NUM,
      SUPPLIER_NUMBER,
      SUPPLIER_CUSTMER_NAME,
      GL_LINE_DESCRIPTION,
      NET_ACCOUNTED
    )))) AS row_id,
    CAST(ENTITY AS STRING) AS ENTITY,
    CAST(GL_SOURCE_NAME AS STRING) AS GL_SOURCE_NAME,
    CAST(GL_CATEGORY AS STRING) AS GL_CATEGORY,
    CAST(JOURNAL_NUMBER AS STRING) AS JOURNAL_NUMBER,
    DATE(SAFE.PARSE_TIMESTAMP('%b %e %Y %I:%M %p', CAST(BOOKING_DATE AS STRING))) AS POSTING_DATE,
    CAST(PERIOD AS STRING) AS PERIOD,
    CAST(ACCOUNT AS STRING) AS ACCOUNT,
    CAST(HFM_ACCOUNT AS STRING) AS HFM_ACCOUNT,
    CAST(HFM_DSCRIPTIONS AS STRING) AS HFM_DSCRIPTIONS,
    CAST(DEPARTMENT AS STRING) AS DEPARTMENT,
    CAST(PRODUCT AS STRING) AS PRODUCT,
    CAST(WORK_ORDER AS STRING) AS WORK_ORDER,
    CAST(IC AS STRING) AS IC,
    CAST(PROJECT AS STRING) AS PROJECT,
    CAST(SYSTEM AS STRING) AS SYSTEM,
    CAST(RESERVE AS STRING) AS RESERVE,
    CAST(INVOICE_NUM AS STRING) AS INVOICE_NUM,
    CAST(SUPPLIER_NUMBER AS STRING) AS SUPPLIER_NUMBER,
    CAST(SUPPLIER_CUSTMER_NAME AS STRING) AS SUPPLIER_CUSTMER_NAME,
    CAST(GL_LINE_DESCRIPTION AS STRING) AS GL_LINE_DESCRIPTION,
    CAST(PO_NUMBER AS STRING) AS PO_NUMBER,
    SAFE_CAST(NET_ACCOUNTED AS NUMERIC) AS AMOUNT,
    CAST(TRANSACTION_TYPE_NAME AS STRING) AS TRANSACTION_TYPE_NAME,
    CAST(GL_TAX AS STRING) AS GL_TAX,
    CAST(SUBLEDGER_TAX_CODE AS STRING) AS SUBLEDGER_TAX_CODE,
    CAST(EMPLOYEE_NAME AS STRING) AS EMPLOYEE_NAME,
    embedding_text,
    CAST(NULL AS ARRAY<FLOAT64>) AS embedding
  FROM source_gl
  WHERE GL_CATEGORY = 'Purchase Invoices'
    AND COALESCE(CAST(TRANSACTION_TYPE_NAME AS STRING), '') != 'Reversal'
    AND NOT ENDS_WITH(department_text, '0000')
    AND NOT REGEXP_CONTAINS(
      UPPER(CONCAT(
        COALESCE(CAST(ACCOUNT AS STRING), ''), ' ',
        COALESCE(CAST(HFM_ACCOUNT AS STRING), ''), ' ',
        COALESCE(CAST(HFM_DSCRIPTIONS AS STRING), ''), ' ',
        COALESCE(CAST(GL_LINE_DESCRIPTION AS STRING), ''), ' ',
        COALESCE(CAST(GL_TAX AS STRING), ''), ' ',
        COALESCE(CAST(SUBLEDGER_TAX_CODE AS STRING), '')
      )),
      r'(^|[^A-Z0-9])(AP|VAT|TAX|CASH)([^A-Z0-9]|$)'
    )
)
SELECT *
FROM clean_gl
WHERE TRIM(embedding_text) != ' |  | ';

SELECT
  COUNT(*) AS clean_training_rows,
  COUNTIF(embedding IS NOT NULL) AS embedded_rows,
  COUNT(DISTINCT SUPPLIER_CUSTMER_NAME) AS vendors,
  COUNT(DISTINCT ACCOUNT) AS accounts,
  COUNT(DISTINCT DEPARTMENT) AS departments,
  COUNTIF(ENDS_WITH(DEPARTMENT, '0000')) AS generic_department_rows_remaining
FROM `{{PROJECT_ID}}.{{DATASET_ID}}.gl_coding_history`;
